### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Chips-fr** [midwan/uae4arm-rpi#1]
I tried your repo on raspbian and get many issue:
it doesn't compile due to RASPBERRY switch not pass into gcc command line (DEFS is not included into CFLAGS). Adding it to flags solve this.
Then it fault when starting. Removing USE_PROFILE=1 solve this.
Then i tried your rpi1 target (on a real rpi1) to try PICASSO96 and it doesn't success to start my A4000 HDD with RTG memory...
In which environment are you compiling ?

**Comment by midwan** [comment]
Sorry, I just discovered that my Makefile need to be updated.
I have been cross compiling this lately, so I missed updating the Makefile with the relevant options.

I've been testing the binaries with stock Raspbian and DietPi, it worked normally in both environments.
I'll fix the Makefile and get back to you after I've tested it.

**Comment by midwan** [comment]
Looks like I got all the flags correctly now. :)

I tested a build for rpi3 and rpi1, both produced a binary without problems.
Sorry for missing out on this.
