### ISSUE TITLE
Default to 200 height resolution

### ISSUE THREAD

**Issue by Fourdee** [midwan/uae4arm-rpi#10]
@midwan 

All the games I have are running in ```200``` height resolution (I'am yet to find one that runs at ```256```). We currently have it set to ```256``` and results in black bar at the bottom of screen.

Could we change the default to ```640x200``` ( currently ```640x256```)?

**Comment by midwan** [comment]
The default can be changed easily, but we should check if it creates a problem with the default "PAL" resolution if the user decides to boot a bog-standard Workbench (1.3-3.1). It might cut-off the bottom 56 lines.

I'll test it out and see.

**Comment by midwan** [comment]
With the recent advancements I made in the SDL2 port, I don't think we need to worry about this one. We can use GPU accelerated displays in SDL2, so it will be super fast and smooth regardless if it's on a 640x480 surface or a 1080p one. 

Actually we should switch to use 1080p always once that is ready, and the GPU will do the scaling. :)

**Comment by Fourdee** [comment]
@midwan 

Sounds good. Keep me updated when ready to test SDL2 👍

**Comment by midwan** [comment]
It's progressing nicely, the GUI is already working (needs some improvements but everything's there) and I need to work a bit on the emulation screen next. I'll let you know.
