### ISSUE TITLE
Saving config files creates duplicate entries sometimes

### ISSUE THREAD

**Issue by midwan** [midwan/uae4arm-rpi#4]
Saving a new configuration sometimes creates duplicate entries in the menu.
The duplicates do not exist as physical files in the conf/ folder.

**Comment by midwan** [comment]
Need specific steps to recreate this, as I can't see the problem in the current build.

**Comment by Fourdee** [comment]
@midwan 
Unable to replicate my end with v2 binary. Saved 20+ configs, all unique entries.

**Comment by midwan** [comment]
Same here. I've asked the user who originally reported this to give me
steps to recreate it.

**Comment by midwan** [comment]
As I haven't heard back from any other user regarding this, not even the one who originally reported it, I will close it for now.

If we get any more details with steps to recreate this (if it's still a problem that is), we can re-open it.
