### ISSUE TITLE
eth0: not found - wlan not found :(

### ISSUE THREAD

**Issue by barnie1989** [midwan/uae4arm-rpi#6]
I can't install the Amiberry... The rasp starts with the SD card, but at the end of the script, eth0: not found... same with wlan.

an other sd card wirh a standard system works...

**Comment by Fourdee** [comment]
@barnie1989 
Which Raspberry Pi model and revision (on board, near RPi logo) are you using?

**Comment by barnie1989** [comment]
P1, 2011.12

At the backside: E1114RS2V13B1.0

**Comment by Fourdee** [comment]
@barnie1989 
256mb or 512mb? Ideally if you can take a picture of the front and back, i'd be grateful.

When you powered on the RPi with the image, did you have a working network cable attached?

**Comment by barnie1989** [comment]
512MB, network cable was attached during all my tests. I booted several times

![6c6e91c6-f75d-4ba7-ac43-204cec5c5530](https://cloud.githubusercontent.com/assets/22058354/18325142/5d69b84c-7540-11e6-9b5c-7bef5e2e4cf3.jpg)
![99f01419-d9bc-45af-bb0a-349f43f3c2a3](https://cloud.githubusercontent.com/assets/22058354/18325144/5d9101e0-7540-11e6-81c1-34d9bbe0db26.jpg)

**Comment by Fourdee** [comment]
@barnie1989 

Thanks for the screenshots :+1: 

I just tested my RPi A 256mb (made in UK). Working fine.

#### Ok, lets try a fresh installation, please do the following:
- Download the image here: http://dietpi.com/downloads/images/DietPi-AmiBerry_RPi-armv6-(Jessie).7z
- Extract it
- Write the image to SD card
- Plug in SD card
- Plug in Ethernet (remove the usb wifi)
- Power on device

If you get the error you mentioned earlier (eth0: not found... ), could you take a picture of the screen with the error please.

**Comment by barnie1989** [comment]
it doesn't work
![b6ba99d1-084f-4a17-bd93-77008b5ecd20](https://cloud.githubusercontent.com/assets/22058354/18328521/6392f4fe-754f-11e6-86aa-bc35b908dd61.jpg)

**Comment by Fourdee** [comment]
@barnie1989 
Thanks for the pic.

Possible causes:
- 4.4.19 firmware 
- eth index higher than 9 (dietpi checks for available eth adapters from 0-9)

> an other sd card wirh a standard system works...

#### Does the official Raspbian Jessie image work on your system? https://www.raspberrypi.org/downloads/raspbian/ 
If so, we can test if 4.4.19 firmware is the cause by running the following on that image:
```
rpi-update
reboot

#check version
uname -a

#ping test
ping google.com
```

#### ifconfig results
Please replicate the picture in your previous post, then:
- Press CTRL+C to cancel connection test
- It should return to cmd line ```#```, if not, you may need to login with ```root``` ```dietpi```
- Type ```ifconfig -a``` then take another picture please

**Comment by midwan** [comment]
@barnie1989 did you get a chance to try out the above suggestion by @Fourdee ?

**Comment by barnie1989** [comment]
I'm not at home, so I need some days...

**Comment by midwan** [comment]
@barnie1989 sure, no problem. As long as we know, we can wait. :)

**Comment by midwan** [comment]
@barnie1989 
Any news on this please?

**Comment by barnie1989** [comment]
the standard image is running! 


is that for your image or the standard image??? 

rpi-update
reboot

#check version
uname -a

#ping test
ping google.com

**Comment by midwan** [comment]
@barnie1989 
Could you please explain a bit more, what you mean by standard image/your image?

It's DietPi in all cases, there's no "my" image in this. :)

Did I understand correctly that it works now?

**Comment by barnie1989** [comment]
please see the last comment from Fourdee

**Comment by midwan** [comment]
I've updated my comment to clarify... :)

Does it work for you after the rpi-update?

**Comment by barnie1989** [comment]
Yes, this image works fine directly after the download:

https://www.raspberrypi.org/downloads/raspbian/

**Comment by midwan** [comment]
And does it work in DietPi if you run the same there?
e.g.:
```
apt-get install rpi-update
rpi-update
reboot
```

**Comment by barnie1989** [comment]
hi had downloaded the raspberry image from http://dietpi.com/ and it works... now it's downloading many files :)

**Comment by midwan** [comment]
Thanks for confirming. :)
